import { useState } from 'react';

export default function ExecutiveReport({ cityData, onClose }) {
  const [copied, setCopied] = useState(false);

  if (!cityData) return null;

  const {
    city,
    region,
    direction,
    confidence,
    explanation,
    key_driver,
    severity,
    median_price,
    price_change_pct,
    inventory,
    inventory_change_pct,
    days_on_market,
    rate,
    bank,
    last_updated,
    news = [],
  } = cityData;

  const dirUpper = (direction || 'stable').toUpperCase();
  const severityLevel = typeof severity === 'number' ? Math.max(1, Math.min(5, severity)) : 1;

  // Format currency
  const formatCurrency = (val) => {
    if (val === null || val === undefined) return 'N/A';
    // NHPI indexes are around 100-130, actual prices are $300k+
    if (val < 2000) return `${val.toFixed(1)} (Index)`;
    return new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 0 }).format(val);
  };

  const formatPercent = (val) => {
    if (val === null || val === undefined) return 'N/A';
    const sign = val > 0 ? '+' : '';
    return `${sign}${val.toFixed(2)}%`;
  };

  // Actionable advice based on signal
  const getBrokerAdvice = () => {
    if (dirUpper === 'HEATING') {
      return {
        strategy: 'Agressive Acquisition & Fast Listing',
        buyers: [
          'Act quickly: home values are rising with high momentum. Expect bidding wars.',
          'Secure pre-approval immediately and consider waving non-essential contingencies.',
          'Look for off-market inventory or newly listed properties to beat competition.',
        ],
        sellers: [
          'Hold out for premium pricing. Multiple-offer scenarios are highly likely.',
          'Prioritize buyers with strong financing or cash offers over marginally higher bids.',
          'Consider short listing periods (e.g. 5-7 days on market before reviewing offers).',
        ],
      };
    } else if (dirUpper === 'COOLING') {
      return {
        strategy: 'Patience for Buyers, Prudent Pricing for Sellers',
        buyers: [
          'Negotiate aggressively: inventory is building, and sellers are losing leverage.',
          'Request seller concessions (closing cost credits, repair credits, rate buy-downs).',
          'Take your time — the risk of overpaying is high; compare multiple options.',
        ],
        sellers: [
          'Price aggressively below recent comparable sales to attract dwindling demand.',
          'Address all minor repairs and staging before listing to stand out.',
          'Be open to early negotiations and flexible terms; avoid letting properties sit.',
        ],
      };
    } else {
      return {
        strategy: 'Opportunistic Buying & Stable Selling',
        buyers: [
          'Focus on long-term value; the stable market environment reduces speculative risk.',
          'Bargaining power is balanced — use days-on-market metrics to spot stale listings.',
          'Ideal time for lock-in transactions if favorable fixed mortgage rates are secured.',
        ],
        sellers: [
          'Expect normal transaction timelines (15-40 days on market). Avoid panic pricing.',
          'Set prices accurately at fair market value based on recent local comps.',
          'Focus on traditional marketing and high-quality representation to draw qualified buyers.',
        ],
      };
    }
  };

  const advice = getBrokerAdvice();

  // Generate markdown content for clipboard
  const generateMarkdownReport = () => {
    const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    return `# Executive Market Intelligence Report: ${city}, ${region}
Generated on ${today} | Market Watch AI Analyst

## Market Status Summary
- **Signal Direction**: ${dirUpper}
- **Confidence Rating**: ${(confidence || 'Low').toUpperCase()}
- **Severity Level**: ${severityLevel} / 5
- **Primary Market Driver**: ${key_driver || 'Unknown'}

### Executive Commentary
"${explanation}"

---

## Key Performance Indicators (KPIs)
| Metric | Value | Monthly Trend |
| :--- | :--- | :--- |
| **Median Listing Price** | ${formatCurrency(median_price)} | ${formatPercent(price_change_pct)} |
| **Active Inventory** | ${inventory !== null ? inventory : 'N/A'} listings | ${formatPercent(inventory_change_pct)} |
| **Median Days on Market** | ${days_on_market !== null ? `${days_on_market} days` : 'N/A'} | Market Velocity |
| **Macro Interest Rate** | ${rate !== null ? `${rate}%` : 'N/A'} | Central Bank: ${bank || 'N/A'} |

---

## Actionable Broker Strategies & Advice
**Recommended Strategy**: ${advice.strategy}

### For Buyers:
${advice.buyers.map((b) => `- ${b}`).join('\n')}

### For Sellers:
${advice.sellers.map((s) => `- ${s}`).join('\n')}

---
*Disclaimer: Generated by Market Watch AI intelligence. For broker/agent training and educational purposes only. Market metrics fluctuate daily.*
`;
  };

  const handleCopyMarkdown = () => {
    navigator.clipboard.writeText(generateMarkdownReport());
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handlePrint = () => {
    window.print();
  };

  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  return (
    <div className="fixed inset-0 z-50 overflow-y-auto bg-obsidian/70 backdrop-blur-sm flex justify-center p-4 sm:p-6 print:p-0 print:bg-white print:relative print:inset-auto">
      {/* Printable page layout */}
      <div className="bg-white rounded-2xl max-w-4xl w-full p-6 sm:p-10 shadow-2xl flex flex-col gap-6 my-auto print:shadow-none print:my-0 print:p-0">
        
        {/* Top controls (hidden in print) */}
        <div className="flex items-center justify-between border-b border-mist pb-4 print:hidden">
          <span className="text-xs font-semibold uppercase tracking-wider text-smoke/70">
            Executive Report Tool
          </span>
          <div className="flex items-center gap-2">
            <button
              onClick={handleCopyMarkdown}
              className="inline-flex items-center gap-1 bg-mist hover:bg-limestone text-graphite text-xs font-semibold px-3 py-1.5 rounded-lg shadow-sm"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M15.75 17.25v3.375c0 .621-.504 1.125-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.875c0-.621.504-1.125 1.125-1.125H5.25m11.9-3.664A2.251 2.251 0 0015 2.25h-3a2.251 2.251 0 00-2.15 1.586m5.8 0c.065.21.1.433.1.664v.75h-6V4.5c0-.231.035-.454.1-.664M6.75 7.375c0-.621.504-1.125 1.125-1.125h9.75c.621 0 1.125.504 1.125 1.125V16.5a1.125 1.125 0 01-1.125 1.125h-9.75a1.125 1.125 0 01-1.125-1.125V7.375z" />
              </svg>
              {copied ? 'Copied Markdown!' : 'Copy Markdown'}
            </button>
            <button
              onClick={handlePrint}
              className="inline-flex items-center gap-1 bg-obsidian hover:bg-graphite text-bone text-xs font-semibold px-3 py-1.5 rounded-lg shadow-sm"
            >
              <svg className="w-3.5 h-3.5" fill="none" viewBox="0 0 24 24" strokeWidth={2} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6.72 13.82l2.6-2.6m0 0l2.6 2.6m-2.6-2.6V18m6-9h.712c1.432 0 2.567 1.184 2.484 2.614l-.32 5.518a2.5 2.5 0 01-2.484 2.368H6.568a2.5 2.5 0 01-2.484-2.368l-.32-5.518c-.083-1.43 1.052-2.614 2.484-2.614H7m3-6v3m0-3h10M3 21h18" />
              </svg>
              Print / Save PDF
            </button>
            <button
              onClick={onClose}
              className="text-smoke hover:text-obsidian p-1 rounded bg-mist/50 hover:bg-mist"
            >
              <svg className="w-4 h-4" fill="none" viewBox="0 0 24 24" strokeWidth={2.5} stroke="currentColor">
                <path strokeLinecap="round" strokeLinejoin="round" d="M6 18L18 6M6 6l12 12" />
              </svg>
            </button>
          </div>
        </div>

        {/* Report Content */}
        <div className="flex flex-col gap-6 text-graphite font-sans">
          {/* Cover Header */}
          <div className="flex flex-col gap-2 border-b-2 border-obsidian pb-5">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-widest text-ember">
                Market Watch Analyst Intel
              </span>
              <span className="text-xs font-medium text-smoke/70">
                {today}
              </span>
            </div>
            <h1 className="text-2xl sm:text-3xl font-extrabold text-obsidian tracking-tight uppercase">
              Real Estate Market Intelligence Report
            </h1>
            <p className="text-sm font-semibold text-smoke">
              Detailed micro-economic review for <strong className="text-obsidian font-bold">{city}, {region}</strong>
            </p>
          </div>

          {/* Status Panel */}
          <div className="grid grid-cols-2 sm:grid-cols-4 gap-4 bg-bone/70 border border-mist p-4 rounded-xl">
            <div className="flex flex-col gap-0.5">
              <span className="text-[10px] text-smoke/75 uppercase tracking-wider font-semibold">Signal Direction</span>
              <span className={`text-base font-bold uppercase tracking-wide ${
                dirUpper === 'HEATING' ? 'text-ember' : dirUpper === 'COOLING' ? 'text-smoke' : 'text-graphite'
              }`}>
                {dirUpper}
              </span>
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-[10px] text-smoke/75 uppercase tracking-wider font-semibold">Confidence Rating</span>
              <span className="text-base font-bold text-obsidian uppercase">
                {confidence || 'LOW'}
              </span>
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-[10px] text-smoke/75 uppercase tracking-wider font-semibold">Severity Index</span>
              <div className="flex items-center gap-1 mt-1">
                {[1, 2, 3, 4, 5].map((dot) => (
                  <span
                    key={dot}
                    className={`w-2.5 h-2.5 rounded-full ${
                      dot <= severityLevel ? 'bg-ember' : 'bg-limestone'
                    }`}
                  />
                ))}
              </div>
            </div>
            <div className="flex flex-col gap-0.5">
              <span className="text-[10px] text-smoke/75 uppercase tracking-wider font-semibold">Primary Driver</span>
              <span className="text-xs font-bold text-obsidian truncate">
                {key_driver || 'Interest Rates'}
              </span>
            </div>
          </div>

          {/* Executive Commentary */}
          <div className="flex flex-col gap-2">
            <h3 className="text-sm font-bold uppercase tracking-wider text-obsidian border-b border-mist pb-1">
              Executive Commentary
            </h3>
            <p className="text-sm leading-relaxed text-graphite font-serif italic text-justify bg-bone/30 p-4 border-l-4 border-ember rounded-r-lg">
              "{explanation || 'Analysis temporarily unavailable for this market area.'}"
            </p>
          </div>

          {/* KPI Matrix Table */}
          <div className="flex flex-col gap-2">
            <h3 className="text-sm font-bold uppercase tracking-wider text-obsidian border-b border-mist pb-1">
              Key Performance Indicators (KPIs)
            </h3>
            <div className="overflow-x-auto border border-mist rounded-xl shadow-sm">
              <table className="min-w-full divide-y divide-mist text-sm text-left">
                <thead className="bg-bone/80 text-[10px] uppercase font-bold text-smoke tracking-wider">
                  <tr>
                    <th scope="col" className="px-6 py-3">Market Metric</th>
                    <th scope="col" className="px-6 py-3">Current Value</th>
                    <th scope="col" className="px-6 py-3 text-right">Trend / Macro Context</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-mist bg-white font-medium">
                  <tr>
                    <td className="px-6 py-3.5 font-bold text-obsidian">Median Listing Price</td>
                    <td className="px-6 py-3.5 text-graphite font-semibold">{formatCurrency(median_price)}</td>
                    <td className={`px-6 py-3.5 text-right font-bold ${
                      (price_change_pct || 0) > 0 ? 'text-ember' : 'text-smoke'
                    }`}>
                      {formatPercent(price_change_pct)} (MoM)
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-3.5 font-bold text-obsidian">Active Market Supply</td>
                    <td className="px-6 py-3.5 text-graphite font-semibold">{inventory !== null ? `${inventory} Units` : 'N/A'}</td>
                    <td className={`px-6 py-3.5 text-right font-bold ${
                      (inventory_change_pct || 0) > 0 ? 'text-smoke' : 'text-ember'
                    }`}>
                      {formatPercent(inventory_change_pct)} (Supply Change)
                    </td>
                  </tr>
                  <tr>
                    <td className="px-6 py-3.5 font-bold text-obsidian">Median Days on Market</td>
                    <td className="px-6 py-3.5 text-graphite font-semibold">{days_on_market !== null ? `${days_on_market} Days` : 'N/A'}</td>
                    <td className="px-6 py-3.5 text-right text-smoke font-medium">Market Velocity Indicator</td>
                  </tr>
                  <tr>
                    <td className="px-6 py-3.5 font-bold text-obsidian">Interest Rate Environment</td>
                    <td className="px-6 py-3.5 text-graphite font-semibold">{rate !== null ? `${rate}%` : 'N/A'}</td>
                    <td className="px-6 py-3.5 text-right text-smoke font-medium">{bank || 'Central Bank Policy'}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>

          {/* Actionable Recommendations */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-2">
            <div className="bg-bone/45 border border-mist p-5 rounded-xl flex flex-col gap-3">
              <div className="flex items-center gap-2 border-b border-mist pb-2">
                <span className="w-2.5 h-2.5 rounded-full bg-ember shrink-0" />
                <h4 className="text-sm font-bold uppercase tracking-wider text-obsidian">Buyer Strategies</h4>
              </div>
              <ul className="list-disc pl-5 text-xs text-graphite space-y-2 leading-relaxed">
                {advice.buyers.map((item, idx) => (
                  <li key={idx} className="pl-1">{item}</li>
                ))}
              </ul>
            </div>

            <div className="bg-bone/45 border border-mist p-5 rounded-xl flex flex-col gap-3">
              <div className="flex items-center gap-2 border-b border-mist pb-2">
                <span className="w-2.5 h-2.5 rounded-full bg-smoke shrink-0" />
                <h4 className="text-sm font-bold uppercase tracking-wider text-obsidian">Seller Strategies</h4>
              </div>
              <ul className="list-disc pl-5 text-xs text-graphite space-y-2 leading-relaxed">
                {advice.sellers.map((item, idx) => (
                  <li key={idx} className="pl-1">{item}</li>
                ))}
              </ul>
            </div>
          </div>

          {/* News Triggers Considered */}
          {news.length > 0 && (
            <div className="flex flex-col gap-2 print:break-inside-avoid">
              <h3 className="text-sm font-bold uppercase tracking-wider text-obsidian border-b border-mist pb-1">
                News Triggers & Signals Analysed
              </h3>
              <ul className="divide-y divide-mist text-xs text-graphite leading-relaxed">
                {news.slice(0, 3).map((item, idx) => (
                  <li key={idx} className="py-2.5 flex justify-between gap-4">
                    <span className="font-semibold text-obsidian">{item.headline}</span>
                    <span className="text-smoke/60 shrink-0 text-right italic font-medium">{item.source_name}</span>
                  </li>
                ))}
              </ul>
            </div>
          )}

          {/* Footer Disclaimer */}
          <div className="border-t border-mist pt-4 mt-4 flex justify-between text-[10px] text-smoke/50 font-medium">
            <span>Powered by Market Watch AI Intelligence Engine</span>
            <span>Broker Training Use Only</span>
          </div>

        </div>

      </div>
    </div>
  );
}
